### ISSUE TITLE
Replace ->over with ->requires

### ISSUE THREAD

**Issue by jberger** [powerman/perl-Mojolicious-Plugin-JSONRPC2#1]
As of Mojolicious 9.0 the ->over method is now ->requires https://github.com/mojolicious/mojo/blob/bd3a50d4f2c53ce5be06706cfdf05d0771a1bf78/Changes#L80

I see that you're providing a condition so your module itself looks ok but the tests and documentation need fixes

**Comment by powerman** [comment]
Fixed in 2.0.2. Don't you guys get tired of making incompatible changes? Look at Go - 11 years of 100% compatibility with Go 1 so far… and it's really pleasure to work with, no matter there some minor things became a bit ugly because of this.

**Comment by jberger** [comment]
Go is written by a massive company with near infinite money and a huge development team. We do our best to balance compatibility with progress while keeping maintainability. Yes it is a different ethos than the rest of Perl (and vs Go too I guess) but we hope that our end product is worthwhile as a result. Sorry for your inconvenience.
